### ISSUE TITLE
Printing movement stuttering with Mattercontrol

### ISSUE THREAD

**Issue by stephenci** [donovan6000/iMe#12]
as you might have known. I thought it would also be best to include here as an issue to be tracked.

While printing the print movement suffer considerably stuttering move. Slowing the print down helps but it still there.

**Comment by unlimitedbacon** [comment]
MatterControl breaks up longer moves into short segments. This is probably what is causing the stuttering.

**Comment by donovan6000** [comment]
This is fixed in the latest version V00.00.01.06

**Comment by qwerty8224** [comment]
I confirm.
