### ISSUE TITLE
Mattercontrol

### ISSUE THREAD

**Issue by qwerty8224** [donovan6000/iMe#13]
Sorry that I write here !!!
Moderator Matternachkers asks  profiles that would add to program the printer M3D
quote
Hardware and software third party, which regularly takes GCode. This is great news. I'll see if we can get a profile in the MC. Are there any existing or Cura Slic3r profiles we could base it on?

**Comment by ra100** [comment]
I think you could use profiles from M3D-Fio https://github.com/donovan6000/M3D-Fio/tree/devel/octoprint_m3dfio/static/profiles

**Comment by qwerty8224** [comment]
Maybe it's wrong but I think that it is necessary consent Donovan6000 And yours too )))

**Comment by donovan6000** [comment]
The profiles ra100 linked to are the latest ones that we've been working on, so they should be good.

You could also ask @stephenci for a MatterControl profile for the Micro 3D. [He's done some experimenting with getting them to work nicely together](https://www.youtube.com/watch?v=FXfaQPzQaWw).

**Comment by stephenci** [comment]
I had the basic setting changed to suit M3D but not thoroughly yet. I'm waiting for the firmware that will fix stuttering issue and then I'll find time the setting some more and upload the profile. Would it help to upload profile here in this hub?
