### ISSUE TITLE
Check G32 stops the left rear

### ISSUE THREAD

**Issue by qwerty8224** [donovan6000/iMe#34]
IME 1.11 It is right ???

**Comment by donovan6000** [comment]
I now have G32 move back to the center when it's done. Try out the latest devel version of iMe, [V00.00.01.12](https://github.com/donovan6000/iMe/tree/devel), and let me know if you have any other problems.

Thanks for testing :)

**Comment by qwerty8224** [comment]
It moves to the center but does not perform sensing center. It is right ???

**Comment by donovan6000** [comment]
It doesn't need to perform sensing on the center at the end. I only had it do it before because it somehow reduced iMe's size.

**Comment by qwerty8224** [comment]
ааааа  Then all super))))

**Comment by donovan6000** [comment]
Awesome. I'll probably release iMe later today then. Thanks for all the help.
