### ISSUE TITLE
Z Skips team

### ISSUE THREAD

**Issue by qwerty8224** [donovan6000/iMe#38]
IME 1.12 1.13 skips lifting team
Check, please.

**Comment by qwerty8224** [comment]
Error Mattecontrol
Octoprint M33Fio

**Comment by donovan6000** [comment]
I don't understand what you mean. What's lifting team?

**Comment by qwerty8224** [comment]
Skips Team Z 
Nozzle (extruder) does not rise

**Comment by donovan6000** [comment]
I still don't understand. What is Skips Team Z? Is it a G-code command?

iMe wont lift the nozzle if the 3D printing software doesn't send the command to make the nozzle rise. Are you sure this isn't an issue with MatterControl and OctoPrint?

**Comment by qwerty8224** [comment]
It is difficult to communicate with Google translator)))
I do not know what the problem is))) I think you can see the Problem in the firmware. 1.12. Before, everything was fine. I tested 1.12 Devel had no problems.

**Comment by qwerty8224** [comment]
I do not understand ...... /////// 1.14 is good prints
Everything works as it should.
