### ISSUE TITLE
 Z X Y is broken 1.18 Movement is big

### ISSUE THREAD

**Issue by qwerty8224** [donovan6000/iMe#42]
The value ZXY wrong in going with M3D manager at MatteContro

M3D manager do Feedrate 1500mm / c default

**Comment by qwerty8224** [comment]
Once!!! XYZ values transfer correctly

**Comment by donovan6000** [comment]
I tried about 20 times to recreate this issue, but so far I've haven't had any problems. None of my X, Y, or Z values are corrupted when switching between M33 Manager and MatterControl.
![transfer](https://cloud.githubusercontent.com/assets/6620767/18111671/6ce66d62-6ed6-11e6-9d37-9b979c0ec7a2.png)

Can you post everything in MatterControl's terminal output when you experience this issue?

**Comment by qwerty8224** [comment]
Ok how to get problemmu. 
Ultimaker I finish a project and do not touch the printer .... until it works well)))

**Comment by qwerty8224** [comment]
From Mattecointrol a M3D manager
![1](https://cloud.githubusercontent.com/assets/19486373/18139106/a118c818-6fb8-11e6-9fe7-531682faccdb.png)

**Comment by qwerty8224** [comment]
IME 1.20 problem (

**Comment by donovan6000** [comment]
I still haven't been able to recreate this issue. Does it happen if you try it on another computer?

**Comment by qwerty8224** [comment]
Strange .... What you do not have a problem !!!! Maybe I do not have ....
I check the house again from scratch.

**Comment by donovan6000** [comment]
Do you still have this problem when using an [older version of M33 Manager](https://github.com/donovan6000/iMe/releases)?

**Comment by qwerty8224** [comment]
I have a problem there.
This happens when you switch M33 Mod Bootloader
Firmvare mod

**Comment by donovan6000** [comment]
This problems happens for you when switching between firmware mode and bootloder mode using only M33 Manager?

**Comment by qwerty8224** [comment]
Yes

**Comment by donovan6000** [comment]
Does the problem happen with older versions of M33 Manager?

**Comment by qwerty8224** [comment]
Yes v0.10 v0.12 problemm
It may be a bug in the driver?

**Comment by donovan6000** [comment]
Does it happen with the first version of M33 Manager [V0.1](https://github.com/donovan6000/iMe/archive/V00.00.00.06.zip)?

**Comment by qwerty8224** [comment]
all ok no problems
X And Y  jErk also works fine

**Comment by donovan6000** [comment]
I just realized that version of M33 Manager doesn't have a button that lets you switch to bootloader mode. M33 Manager [V0.05](https://github.com/donovan6000/iMe/archive/V00.00.00.09.zip) was the first version that has that button.

**Comment by qwerty8224** [comment]
ок check now!

2016-09-22 0:34 GMT+03:00 donovan6000 notifications@github.com:

**Comment by qwerty8224** [comment]
V0.05 there is an error

**Comment by qwerty8224** [comment]
V 0.05 there is an error

2016-09-22 0:34 GMT+03:00 donovan6000 notifications@github.com:

**Comment by donovan6000** [comment]
I still have no idea what's causing the problem. Can you try [every version of M33 Manager](https://github.com/donovan6000/iMe/releases) and let me know which versions don't cause this issue?

**Comment by qwerty8224** [comment]
OK . How to check'll let you know.
