### ISSUE TITLE
iMe hex too big

### ISSUE THREAD

**Issue by WilliamRodriguez42** [donovan6000/iMe#52]
When building the hex from source (no changes where made) the file is too large to upload. M33 Manager gives the error "Failed to update firmware" and the console says "1900000123.hex is too big." The hex was built on windows, mac, and linux using the avr toolchain 8 bit version. Used mingw on windows. Same result on all operating systems.

**Comment by donovan6000** [comment]
I've only been able to successfully compile it to be small enough on Linux. [It doesn't look like the linker time optimizations work on Windows](https://github.com/donovan6000/iMe/issues/50#issuecomment-281890888), and I haven't tried compiling it on macOS.

Make sure your using the latest AVR 8-bit toolchain, [V3.5.4](http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORLINUX.aspx) and that the [locations in the Makefile](https://github.com/donovan6000/iMe/blob/master/Makefile#L14-L17) correctly point to the toolchain binaries.
