### ISSUE TITLE
Question: Bootloader

### ISSUE THREAD

**Issue by sam-dyer** [donovan6000/iMe#59]
Sorry this is not an issue but I don't know where to put a question.

 If I install iMe firmware through M33 fio will I have to get the printer out of bootloader or not and If so how?

**Comment by donovan6000** [comment]
M33 Fio automatically switches the printer into firmware mode whenever it connects to the printer.

The only time you'll have to manually switch the printer into firmware mode yourself is when you using software other than M33 Fio.
