### ISSUE TITLE
Is there a way to limit bed size in firmware

### ISSUE THREAD

**Issue by guysoft** [donovan6000/iMe#66]
Hey, 

Related to this issue https://github.com/donovan6000/M33-Fio/issues/253

Also discussion here: https://discourse.octoprint.org/t/m3d-lmiting-bed-size-and-cura-first-travel-to-front-left/4614/5

**Comment by donovan6000** [comment]
The bed size is [hard coded in the firmware](https://github.com/donovan6000/iMe/blob/master/motors.cpp#L25-L48), so you'd have to change it at the source and recompile it.
